plugins:
  sparkloc_enabled:
    default: true
    client: true
  sparkloc_discourse_sso_secret:
    default: ""
    client: false
    secret: true
  sparkloc_oauth2_issuer_url:
    default: "https://sparkloc.com/oauth-provider"
    client: false
  sparkloc_creem_enabled:
    default: false
    client: true
  sparkloc_creem_api_key:
    default: ""
    client: false
    secret: true
  sparkloc_creem_webhook_secret:
    default: ""
    client: false
    secret: true
  sparkloc_creem_product_id:
    default: ""
    client: false
  sparkloc_creem_group_name:
    default: "vip"
    client: false
  sparkloc_creem_test_mode:
    default: false
    client: false
  sparkloc_deeplx_enabled:
    default: false
    client: true
  sparkloc_deeplx_api_url:
    default: "https://deeplx.sparkloc.org"
    client: false
  sparkloc_deeplx_admin_token:
    default: ""
    client: false
    secret: true
