plugins:
  sparkloc_enabled:
    default: true
    client: true
  sparkloc_backend_url:
    default: "https://auth.sparkloc.com"
    client: false
  sparkloc_internal_api_key:
    default: ""
    client: false
    secret: true
